/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.springframework.obm.avro.crm;

@SuppressWarnings("all")
public interface Crm {
    public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Crm\",\"namespace\":\"org.springframework.obm.avro.crm\",\"types\":[{\"type\":\"record\",\"name\":\"Customer\",\"fields\":[{\"name\":\"firstName\",\"type\":[\"string\",\"null\"]},{\"name\":\"lastName\",\"type\":[\"string\",\"null\"]},{\"name\":\"email\",\"type\":[\"string\",\"null\"]},{\"name\":\"id\",\"type\":[\"int\",\"null\"]}]},{\"type\":\"record\",\"name\":\"User\",\"fields\":[{\"name\":\"email\",\"type\":[\"string\",\"null\"]},{\"name\":\"password\",\"type\":[\"string\",\"null\"]}]}],\"messages\":{\"createCustomer\":{\"request\":[{\"name\":\"fn\",\"type\":\"string\"},{\"name\":\"ln\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"}],\"response\":\"Customer\"}}}");

    org.springframework.obm.avro.crm.Customer createCustomer(java.lang.CharSequence fn, java.lang.CharSequence ln, java.lang.CharSequence email) throws org.apache.avro.AvroRemoteException;
}
