/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.springframework.obm.avro.crm;

@SuppressWarnings("all")
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"org.springframework.obm.avro.crm\",\"fields\":[{\"name\":\"firstName\",\"type\":[\"string\",\"null\"]},{\"name\":\"lastName\",\"type\":[\"string\",\"null\"]},{\"name\":\"email\",\"type\":[\"string\",\"null\"]},{\"name\":\"id\",\"type\":[\"int\",\"null\"]}]}");
    public java.lang.CharSequence firstName;
    public java.lang.CharSequence lastName;
    public java.lang.CharSequence email;
    public java.lang.Integer id;

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return firstName;
            case 1:
                return lastName;
            case 2:
                return email;
            case 3:
                return id;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                firstName = (java.lang.CharSequence) value$;
                break;
            case 1:
                lastName = (java.lang.CharSequence) value$;
                break;
            case 2:
                email = (java.lang.CharSequence) value$;
                break;
            case 3:
                id = (java.lang.Integer) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
}
